---
name: Check versions of overlayed ports and reports about mismatches

on:
  workflow_dispatch:
  schedule:
    - cron: "15 1 * * *"

jobs:
  check-and-inform:
    runs-on: crux-3.8
    steps:
      - name: Restore ports
        id: load-ports
        uses: actions/cache/restore@v4
        with:
          path: /usr/ports
          key: ports-xorg-riscv64-${{ github.ref_name }}

      - name: enable all repositories
        run: |
          cd /etc/ports
          for i in *.inactive; do mv $i ${i/.inactive/}; done
          echo host=crux.nu > /etc/ports/xorg-riscv64.rsync
          echo collection=crux-riscv/xorg-riscv64/3.8/ >> /etc/ports/xorg-riscv64.rsync
          echo destination=/usr/ports/xorg-riscv64 >> /etc/ports/xorg-riscv64.rsync
          ports -u

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run script and create tickets
        env:
          GITEA_TOKEN: ${{ secrets.CRUXBOT_TOKEN }}
          GITEA_URL: 'https://git.crux.nu'
          GITEA_OWNER: crux-riscv
          GITEA_REPO: xorg-riscv64
        run: |
          bash -x ${{ github.workspace }}/.gitea/scripts/overlay_versions.sh /usr/ports/xorg-riscv64 xorg

      - name: Save ports to cache
        id: save-ports
        if: always()
        uses: actions/cache/save@v4
        with:
          path: /usr/ports
          key: ${{ steps.load-ports.outputs.cache-primary-key }}
